name: Deploy images to GHCR

on:
  push:
    branches:
      - main
      - dev

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.AUTH_TOKEN}}

      - name: "Build Images"
        run: |
          docker build --tag ghcr.io/proxycroak-nginx/store:latest nginx
          docker built --tag ghcr.io/proxycroak-web/store:latest .
          docker push ghcr.io/proxycroak-web/store:latest
          docker push ghcr.io/proxycroak-nginx/store:latest