name: Deploy images to GHCR

on:
  push:
    branches:
      - main
      - dev

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.AUTH_TOKEN }}

      - name: Extract metadata (tags, labels) for web container
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/proxycroak-web

      - name: Build and push Docker web image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/proxycroak-web:latest
          labels: ${{ steps.meta.outputs.labels }}


      - name: Extract metadata (tags, labels) for nginx container
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/proxycroak-nginx


      - name: Build and push Docker nginx image
        uses: docker/build-push-action@v4
        with:
          context: nginx
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/proxycroak-nginx:latest
          labels: ${{ steps.meta.outputs.labels }}

