name: Discord Notification

on:
  push:
    branches:
      - main


jobs:
  notify:
    permissions: read-all
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract PR Info
      uses: 8BitJonny/gh-get-current-pr@master
      id: PR
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ github.event.pull_request.head.sha }}
        filterOutClosed: false
        filterOutDraft: true


    - name: Send Discord notification
      if: success() && steps.PR.outputs.number
      env:
        prTitle: ${{ steps.PR.outputs.pr_title }}
        prBody: ${{ steps.PR.outputs.pr_body }}

      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        content: "<@&1190582363340685424> **New release!**"
        embed-title: "Proxycroak ${{env.prTitle}}"
        embed-description: "${{env.prBody}}"
        embed-url: "https://proxycroak.com/changelog#${{env.prTitle}}"
        embed-thumbnail-url: "https://proxycroak.com/static/img/favicons/favicon-196x196.png"
        embed-color: "5763719"